name: test-action
on:
  workflow_dispatch:
  push:
#branches: 'develop'
# develop 브랜치를 타겟으로 잡음
# 아무것도 입력안하면 모든 브랜치를 타겟으로 잡음
# 풀리퀘스트도 가능
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        run: ./gradlew test